// Ghana Emergency Hotlines Database
// Sources: Ghana Health Service, Ghana Police Service, NADMO, NITA

export const EMERGENCY_HOTLINES = [
  {
    id: 'ambulance',
    name: 'Ambulance Service',
    nameTwi: 'Ambulance Sεhwie',
    number: '193',
    category: 'medical',
    icon: '🚑',
    description: 'National Ambulance Service',
    available: '24/7',
  },
  {
    id: 'police',
    name: 'Ghana Police Service',
    nameTwi: 'Polisi',
    number: '191',
    category: 'police',
    icon: '🚔',
    description: 'Emergency police response',
    available: '24/7',
  },
  {
    id: 'fire',
    name: 'Ghana Fire Service',
    nameTwi: 'Ogya Sεhwie',
    number: '192',
    category: 'fire',
    icon: '🚒',
    description: 'Fire and rescue operations',
    available: '24/7',
  },
  {
    id: 'nadmo',
    name: 'NADMO',
    nameTwi: 'NADMO',
    number: '0800-111-222',
    category: 'disaster',
    icon: '⚠️',
    description: 'National Disaster Management',
    available: '24/7',
  },
  {
    id: 'poison',
    name: 'Poison Control',
    nameTwi: 'Dεdεw Tumi',
    number: '0302-665-401',
    category: 'medical',
    icon: '☠️',
    description: 'Korle-Bu Poison Unit',
    available: 'Office hours',
  },
  {
    id: 'korlebu',
    name: 'Korle-Bu Teaching Hospital',
    nameTwi: 'Korle-Bu Yadeεhaw',
    number: '0302-665-401',
    category: 'hospital',
    icon: '🏥',
    description: "Ghana's main referral hospital",
    available: '24/7',
    city: 'Accra',
  },
  {
    id: '37military',
    name: '37 Military Hospital',
    nameTwi: '37 Asrafohaw',
    number: '0302-776-111',
    category: 'hospital',
    icon: '🏥',
    description: 'Military and civilian emergencies',
    available: '24/7',
    city: 'Accra',
  },
  {
    id: 'ridge',
    name: 'Ridge Hospital',
    nameTwi: 'Ridge Yadeεhaw',
    number: '0302-663-185',
    category: 'hospital',
    icon: '🏥',
    description: 'Greater Accra Regional Hospital',
    available: '24/7',
    city: 'Accra',
  },
  {
    id: 'redcross',
    name: 'Ghana Red Cross',
    nameTwi: 'Ghana Red Cross',
    number: '0302-772-714',
    category: 'ngo',
    icon: '🏥',
    description: 'Emergency humanitarian aid',
    available: 'Office hours',
  },
];

export const CATEGORIES = {
  medical: { label: 'Medical', color: '#D32F2F' },
  police: { label: 'Police', color: '#1565C0' },
  fire: { label: 'Fire', color: '#E65100' },
  disaster: { label: 'Disaster', color: '#6A1B9A' },
  hospital: { label: 'Hospital', color: '#00695C' },
  ngo: { label: 'NGO / Aid', color: '#37474F' },
};